config/routes.rb
Rails.application.routes.draw do

  root 'landings#index'

  namespace :landings, path: '' do
    get 'about'
    get 'index'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index; end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/_boomtime.html.haml
.row
  / row
  .col-md-10.col-md-offset-1
    / Left Blogrol col 8
    .works-block
      / Post Wrapper
      %h2#boomtime #BoomTime
      %hr/
      %img.img-responsive.featured{:alt => "...", :src => "http://placehold.it/1000x600"}/
      %h5.media-heading
        %strong Vel donec et scelerisque vestibulum. Condimentum aliquam, mollit magna velit nec
      %hr/
    / end Post Wrapper
  / end Left content col 8
  .col-md-5.col-md-offset-1
    / Blog Sidebar
    %p Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
    %hr/
    %dl.dl-horizontal.text-left
      %dt Date:
      %dd Jan 25, 2014
      %dt Skills Related:
      %dd Web Design, UI Design
      %dt Client:
      %dd Mark Szuckerburg
      %dt Website:
      %dd WeAreCool.Com
    %nav
      %ul.pagination
        %li
          %a{"aria-label" => "Previous", :href => "#"}
            %span{"aria-hidden" => "true"} Prev
        %li
          %a{"aria-label" => "Next", :href => "#"}
            %span{"aria-hidden" => "true"} Next
  / end right content col 4
  .col-md-5
    .row
      .col-md-12
        %h4.text-uppercase Related Item
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/

app/views/landings/_entertainer.html.haml
.row
  / row
  .col-md-10.col-md-offset-1
    / Left Blogrol col 8
    .works-block
      / Post Wrapper
      %h2#entertainer Entertainer
      %hr/
      %img.img-responsive.featured{:alt => "...", :src => "http://placehold.it/1000x600"}/
      %h5.media-heading
        %strong Vel donec et scelerisque vestibulum. Condimentum aliquam, mollit magna velit nec
      %hr/
    / end Post Wrapper
  / end Left content col 8
  .col-md-5.col-md-offset-1
    / Blog Sidebar
    %p Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
    %hr/
    %dl.dl-horizontal.text-left
      %dt Date:
      %dd Jan 25, 2014
      %dt Skills Related:
      %dd Web Design, UI Design
      %dt Client:
      %dd Mark Szuckerburg
      %dt Website:
      %dd WeAreCool.Com
    %nav
      %ul.pagination
        %li
          %a{"aria-label" => "Previous", :href => "#"}
            %span{"aria-hidden" => "true"} Prev
        %li
          %a{"aria-label" => "Next", :href => "#"}
            %span{"aria-hidden" => "true"} Next
  / end right content col 4
  .col-md-5
    .row
      .col-md-12
        %h4.text-uppercase Related Item
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/

app/views/landings/_software_engineer.html.haml
.row
  / row
  .col-md-10.col-md-offset-1
    / Left Blogrol col 8
    .works-block
      / Post Wrapper
      %h2#software_engineer Software Engineer
      %hr/
      %img.img-responsive.featured{:alt => "...", :src => "http://placehold.it/1000x600"}/
      %h5.media-heading
        %strong Vel donec et scelerisque vestibulum. Condimentum aliquam, mollit magna velit nec
      %hr/
    / end Post Wrapper
  / end Left content col 8
  .col-md-5.col-md-offset-1
    / Blog Sidebar
    %p Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
    %hr/
    %dl.dl-horizontal.text-left
      %dt Date:
      %dd Jan 25, 2014
      %dt Skills Related:
      %dd Web Design, UI Design
      %dt Client:
      %dd Mark Szuckerburg
      %dt Website:
      %dd WeAreCool.Com
    %nav
      %ul.pagination
        %li
          %a{"aria-label" => "Previous", :href => "#"}
            %span{"aria-hidden" => "true"} Prev
        %li
          %a{"aria-label" => "Next", :href => "#"}
            %span{"aria-hidden" => "true"} Next
  / end right content col 4
  .col-md-5
    .row
      .col-md-12
        %h4.text-uppercase Related Item
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/

app/views/landings/_wrestler.html.haml
.row{"data-spy" => "scroll"}
  / row
  .col-md-10.col-md-offset-1
    / Left Blogrol col 8
    .works-block
      / Post Wrapper
      %h2#wrestler Wrestler
      %hr/
      %img.img-responsive.featured{:alt => "...", :src => "http://placehold.it/1000x600"}/
      %h5.media-heading
        %strong Vel donec et scelerisque vestibulum. Condimentum aliquam, mollit magna velit nec
      %hr/
    / end Post Wrapper
  / end Left content col 8
  .col-md-5.col-md-offset-1
    / Blog Sidebar
    %p Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
    %hr/
    %dl.dl-horizontal.text-left
      %dt Date:
      %dd Jan 25, 2014
      %dt Skills Related:
      %dd Web Design, UI Design
      %dt Client:
      %dd Mark Szuckerburg
      %dt Website:
      %dd WeAreCool.Com
    %nav
      %ul.pagination
        %li
          %a{"aria-label" => "Previous", :href => "#"}
            %span{"aria-hidden" => "true"} Prev
        %li
          %a{"aria-label" => "Next", :href => "#"}
            %span{"aria-hidden" => "true"} Next
  / end right content col 4
  .col-md-5
    .row
      .col-md-12
        %h4.text-uppercase Related Item
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/
      .col-xs-6.col-sm-3.col-md-4
        .work-related-thumb
          %a{:href => "#"}
            %img.img-thumbnail{:alt => "...", :src => "http://placehold.it/140x140"}/

app/views/landings/about.html.haml
.spacer
#about-header
  .container
    .row
      %h1 Nephtali "JustNeph" Rodriguez

      .col-md-10
        %p
          = link_to "Entertainer", "#entertainer", data: {scroll: "true"}
          |
          = link_to "Wrestler", "#wrestler", data: {scroll: "true"}
          |
          = link_to "#BoomTime", "#boomtime", data: {scroll: "true"}
          |
          = link_to "Software Engineer", "#software_engineer", data: {scroll: "true"}


%nav#about-content
  / fullwidth gray background
  .container
    / container
    = render "entertainer"

    = render "wrestler"

    = render "boomtime"

    = render "software_engineer"

app/views/landings/index.html.haml
%a{:name => "about"}
.intro-header
  .container
    .row
      .col-lg-12
        .intro-message
          %h1 JustNeph
          %h3 Entertainer | Wrestler | #BoomTime | Software Engineer
          %hr.intro-divider/
          %ul.list-inline.intro-social-buttons
            %li
              %a.btn.btn-default.btn-lg{:href => "https://twitter.com/JustNeph", target: "_blank"}
                %i.fa.fa-twitter.fa-fw
                %span.network-name Twitter
            %li
              %a.btn.btn-default.btn-lg{:href => "https://instagram.com/JustNeph", target: "_blank"}
                %i.fa.fa-instagram.fa-fw
                %span.network-name Instagram
            %li
              %a.btn.btn-default.btn-lg{:href => "https://facebook.com/JustNephFB", target: "_blank"}
                %i.fa.fa-facebook.fa-fw
                %span.network-name Facebook
            %li
              %a.btn.btn-default.btn-lg{:href => "https://github.com/nrodriguez", target: "_blank"}
                %i.fa.fa-github.fa-fw
                %span.network-name Github

%a{:name => "services"}
.content-section-a
  .container
    .row
      .col-lg-5.col-sm-6
        %hr.section-heading-spacer/
        .clearfix
        %h2.section-heading
          Entertainer
        %p.lead
          Having appeared in his own youtube series, a sketch comedy channel, written rap songs and now starring as one of the supporting cast members for FYI "Married At First Sight: The First Year", Nephtali has tackled multiple mediums of entertainment with his quick witted humor and ability to connect with his viewers...
          = link_to "READ MORE", root_path
      .col-lg-5.col-lg-offset-2.col-sm-6
        = image_tag("ipad.png", class: "img-responsive")
  / /.container
/ /.content-section-a
.content-section-b
  .container
    .row
      .col-lg-5.col-lg-offset-1.col-sm-push-6.col-sm-6
        %hr.section-heading-spacer/
        .clearfix
        %h2.section-heading
          Wrestler
        %p.lead
          Having trained for over 2 years and managing for over 6, JustNeph has begun to take his stake in the independent wrestling scene. Bringing his ferocity and ability to think two steps ahead, he often calls himself the "Wrestling Ring's Mental Chessmaster". Utilizing bone crunching manuevers like his patented "Capture Kick", he has begun to let the independent wrestling world, he is only just beginning... READ MORE
      .col-lg-5.col-sm-pull-6.col-sm-6
        = image_tag("dog.png", class: "img-responsive")
  / /.container
/ /.content-section-b
.content-section-a
  .container
    .row
      .col-lg-5.col-sm-6
        %hr.section-heading-spacer/
        .clearfix
        %h2.section-heading
          \#BoomTime
        %p.lead
          Leading up to 2014, Nephtali struggled with becoming overweight. After his divorce, he began to take his life into his own hands and got back into the gym. It was in this struggle that the #BoomTime movement began. Losing over 40 lbs and gaining his self confidence back, he seeks to help others achieve their own personal goals both in and out of fitness with postive mental attitude and motivational speaking... READ MORE
      .col-lg-5.col-lg-offset-2.col-sm-6
        = image_tag("phones.png", class: "img-responsive")
.content-section-b
  .container
    .row
      .col-lg-5.col-lg-offset-1.col-sm-push-6.col-sm-6
        %hr.section-heading-spacer/
        .clearfix
        %h2.section-heading
          Software Engineer
        %p.lead
          After graduating with his Bachelors of Science with a focus in Game Development, Nephtali began to take to the world of web applications. Having gained over 5 years of experience in his field, he has taken to joy of tackling tough problems and furthering the preaching of good code quality and best practices... READ MORE
      .col-lg-5.col-sm-pull-6.col-sm-6
        = image_tag("dog.png", class: "img-responsive")
  / /.container
/ /.content-section-a

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title JustNephV2
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic'

    = csrf_meta_tags
    %script{"data-dojo-config" => "usePlainJson: true, isDebug: false", :src => "//s3.amazonaws.com/downloads.mailchimp.com/js/signup-forms/popup/embed.js", :type => "text/javascript"}
    :javascript
      require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us11.list-manage.com","uuid":"deb75043bf18b4af189e63059","lid":"cd4a2d60ff"}) })
  %body
    = render "layouts/shared/header"
    = yield
    = render "layouts/shared/footer"

app/views/layouts/shared/_footer.html.haml
%a{:name => "contact"}
.banner
  .container
    .row
      .col-lg-6
        %h2 Connect with @JustNeph
        %br
        %h2 on all social media platforms
      .col-lg-6
        %ul.list-inline.banner-social-buttons
          %li
            %a.btn.btn-default.btn-lg{:href => "https://twitter.com/JustNeph", target: "_blank"}
              %i.fa.fa-twitter.fa-fw
              %span.network-name Twitter
          %li
            %a.btn.btn-default.btn-lg{:href => "https://twitter.com/JustNeph", target: "_blank"}
              %i.fa.fa-facebook.fa-fw
              %span.network-name Facebook
          %li
            %a.btn.btn-default.btn-lg{:href => "https://twitter.com/JustNeph", target: "_blank"}
              %i.fa.fa-instagram.fa-fw
              %span.network-name Instagram
        %ul.list-inline.banner-social-buttons
          %li
            %a.btn.btn-default.btn-lg{:href => "https://twitter.com/JustNeph", target: "_blank"}
              %i.fa.fa-twitch.fa-fw
              %span.network-name Twitch
          %li
            %a.btn.btn-default.btn-lg{:href => "https://twitter.com/JustNeph", target: "_blank"}
              %i.fa.fa-github.fa-fw
              %span.network-name Github
          %li
            %a.btn.btn-default.btn-lg{:href => "https://twitter.com/JustNeph", target: "_blank"}
              %i.fa.fa-pinterest.fa-fw
              %span.network-name Pinterest
%footer
  .container
    .row
      .col-lg-12
        %ul.list-inline
          %li
            %a{:href => "#"} Home
          %li.footer-menu-divider &#8901;
          %li
            %a{:href => "#about"} About
          %li.footer-menu-divider &#8901;
          %li
            %a{:href => "#services"} Services
          %li.footer-menu-divider &#8901;
          %li
            %a{:href => "#contact"} Contact
        %p.copyright.text-muted.small Copyright &#169; Your Company 2014. All Rights Reserved

app/views/layouts/shared/_header.html.haml
= render "layouts/shared/nav"

app/views/layouts/shared/_nav.html.haml
%nav.navbar.navbar-default.navbar-fixed-top.topnav{:role => "navigation"}
  .container.topnav
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand.topnav{:href => "#"} JustNeph
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'About', landings_about_path
          -# %a{:href => "/about"} About
        %li
          %a{href: "http://storenvy.com/JustNeph", target: "_blank"} Merchandise
        %li
          %a{:href => "#contact"} Contact